# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Configuration for the mecanum-wheeled robot.

All robot-specific values live in this file. The default URDF is generated by
``scripts/tools/generate_mecanum_robot.py``: a 0.6 x 0.4 m chassis on four FUJI-type mecanum wheels
(R = 0.1025 m) with 14 freely rotating 45° rollers each, every roller colliding through 6 spheres, and a
pendulum front axle (62 links: PhysX GPU articulations must stay <= 64 links).
If you regenerate it with other dimensions, keep the constants below in sync (see ``wheel_geometry.json``).
"""

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import DCMotorCfg, ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

##
# Paths
##

MECANUM_WS_ROOT = Path(__file__).resolve().parents[4]
"""Root directory of the ``mecanum_ws`` project."""

URDF_PATH = MECANUM_WS_ROOT / "assets" / "robots" / "mecanum" / "robot.urdf"
"""Path of the robot URDF."""

##
# Robot parameters (must match the URDF)
##

BASE_LINK_NAME = "base_link"
"""Name of the root (chassis) link in the URDF. The lidar of the navigation task is attached to it."""

WHEEL_JOINT_NAMES = [
    "front_left_wheel_joint",
    "front_right_wheel_joint",
    "rear_left_wheel_joint",
    "rear_right_wheel_joint",
]
"""Wheel joint names, in the order front-left, front-right, rear-left, rear-right."""

ROLLER_JOINT_NAMES: list[str] | None = [".*_roller_.*_joint"]
"""Regex(es) of the passive roller joints, e.g. ``[".*roller.*"]``. ``None`` if the URDF has no rollers."""

AXLE_JOINT_NAMES = ["front_axle_joint"]
"""Pendulum front axle joint (free swing around x, only damped)."""

AXLE_DAMPING = 1.0
"""Damping of the pendulum front axle [Nm*s/rad]."""

ROLLER_DAMPING = 1.0e-5
"""Viscous damping of the passive roller joints [Nm*s/rad]."""

ROLLER_ARMATURE = 0.0
"""Armature (added rotor inertia) of the roller joints [kg*m^2]."""

WHEEL_JOINT_SIGNS = (1.0, 1.0, 1.0, 1.0)
"""Per-wheel sign so that a positive joint velocity drives the robot forward (flip for mirrored joint axes)."""

WHEEL_RADIUS = 0.1025
"""Wheel (roller envelope) radius [m]."""

WHEEL_BASE_HALF_LENGTH = 0.22
"""Half distance between front and rear axles (lx) [m]."""

TRACK_HALF_WIDTH = 0.26
"""Half distance between left and right wheels (ly) [m]."""

MAX_WHEEL_SPEED = 20.0
"""Maximum commanded wheel angular velocity [rad/s] (~2 m/s)."""

MOTOR_NO_LOAD_SPEED = 30.0
"""DC motor: speed at which the available torque drops to zero [rad/s]."""

MOTOR_STALL_TORQUE = 20.0
"""DC motor: torque at zero speed [Nm]."""

WHEEL_EFFORT_LIMIT = 10.0
"""DC motor: continuous torque limit [Nm]. Well above the traction limit (~3 Nm/wheel at mu = 0.8), so wheels can slip."""

WHEEL_DAMPING = 2.0
"""Velocity gain of the wheel speed controller [Nm*s/rad].

The DC motor model is explicit (torque computed once per physics step), which is only stable for
``WHEEL_DAMPING * dt / (I_wheel + WHEEL_ARMATURE) < 2``; with the values here it is 1.0 at 120 Hz and 0.34 at 360 Hz.
"""

WHEEL_ARMATURE = 0.01
"""Reflected rotor inertia of the geared wheel motor [kg*m^2] (e.g. 1e-5 kg*m^2 rotor behind a 1:30 gearbox)."""

SPAWN_HEIGHT = 0.125
"""Initial height of the base link above the ground [m]."""

FOOTPRINT_HALF_EXTENTS = (0.33, 0.30)
"""Half length (x) and half width (y) of the rectangle enclosing the robot incl. wheels [m].

Chassis 0.30 x 0.20, wheels reach x = lx + R = 0.3225 and y = ly + hub width / 2 = 0.292. The navigation task
terminates when the lidar sees an obstacle closer than this rectangle (a circle would terminate episodes when a
pillar is still > 10 cm beside the robot).
"""

ROLLER_CONTACT_STIFFNESS = 2.0e5
"""Compliant roller-ground contact stiffness [N/m] (polyurethane rollers: ~0.3 mm deflection under a wheel load).

With rigid contacts the rigid wheels hop at the roller transitions (wheels unloaded in up to 30 % of the steps).
PhysX only applies it when it is set on the ground/terrain material, so tasks must copy it there.
"""

ROLLER_CONTACT_DAMPING = 1.0e3
"""Compliant roller-ground contact damping [N*s/m] (damping ratio ~0.4)."""

ROBOT_MATERIAL = sim_utils.RigidBodyMaterialCfg(
    static_friction=1.0,
    dynamic_friction=1.0,
    friction_combine_mode="multiply",
    restitution_combine_mode="multiply",
    compliant_contact_stiffness=ROLLER_CONTACT_STIFFNESS,
    compliant_contact_damping=ROLLER_CONTACT_DAMPING,
)
"""Material of the robot colliders (rollers). The URDF spawner binds no material, so tasks set it as the default
material of the simulation (``sim.physics_material``); the terrain has its own material (multiply-combined)."""


def ground_material(friction: float = 1.0) -> sim_utils.RigidBodyMaterialCfg:
    """Ground/terrain material carrying the roller contact compliance (see :data:`ROLLER_CONTACT_STIFFNESS`)."""
    return sim_utils.RigidBodyMaterialCfg(
        static_friction=friction,
        dynamic_friction=friction,
        friction_combine_mode="multiply",
        restitution_combine_mode="multiply",
        compliant_contact_stiffness=ROLLER_CONTACT_STIFFNESS,
        compliant_contact_damping=ROLLER_CONTACT_DAMPING,
    )

##
# Articulation configuration
##

_actuators = {
    # wheel speed setpoint -> torque through a torque-limited DC motor model (linear torque-speed curve)
    "wheels": DCMotorCfg(
        joint_names_expr=WHEEL_JOINT_NAMES,
        stiffness=0.0,
        damping=WHEEL_DAMPING,
        saturation_effort=MOTOR_STALL_TORQUE,
        effort_limit=WHEEL_EFFORT_LIMIT,
        velocity_limit=MOTOR_NO_LOAD_SPEED,
        armature=WHEEL_ARMATURE,
    ),
}
# passive pendulum front axle
_actuators["axle"] = ImplicitActuatorCfg(joint_names_expr=AXLE_JOINT_NAMES, stiffness=0.0, damping=AXLE_DAMPING)
if ROLLER_JOINT_NAMES:
    # passive rollers: no drive, only bearing damping. Keep it small: on a 12 mm roller 1e-3 Nm*s/rad already resists
    # rolling with ~2 N at 0.3 m/s and visibly distorts the kinematics
    _actuators["rollers"] = ImplicitActuatorCfg(
        joint_names_expr=ROLLER_JOINT_NAMES, stiffness=0.0, damping=ROLLER_DAMPING, armature=ROLLER_ARMATURE
    )

MECANUM_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        asset_path=str(URDF_PATH),
        fix_base=False,
        merge_fixed_joints=True,
        make_instanceable=True,
        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(
            target_type="velocity",
            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0.0, damping=0.0),
        ),
        activate_contact_sensors=False,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=1,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, SPAWN_HEIGHT),
        joint_pos={".*": 0.0},
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=1.0,
    actuators=_actuators,
)
"""Configuration of the mecanum robot spawned from URDF."""
