# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Configuration of our own (real) mecanum robot.

Geometry measured from its CAD STL (``assets/robots/own_mecanum/stl``, ``scripts/tools/analyze_wheel_mesh.py``); the
URDF is generated by ``scripts/tools/generate_mecanum_robot.py --config assets/robots/own_mecanum/robot_config.json``:
rigid chassis, four 60.6 mm wheels with 9 rubber-coated 45 deg rollers each (6 collision spheres per roller), 41 links.

Same constant names as :mod:`mecanum_ws.robots.mecanum`, so tools can switch robots (``--robot own``).
Masses, motor and rubber contact are GUESSES until they are measured (see ``robot_config.json``).
"""

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import DCMotorCfg, ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

MECANUM_WS_ROOT = Path(__file__).resolve().parents[4]
URDF_PATH = MECANUM_WS_ROOT / "assets" / "robots" / "own_mecanum" / "robot.urdf"

BASE_LINK_NAME = "base_link"
WHEEL_JOINT_NAMES = [
    "front_left_wheel_joint",
    "front_right_wheel_joint",
    "rear_left_wheel_joint",
    "rear_right_wheel_joint",
]
ROLLER_JOINT_NAMES = [".*_roller_.*_joint"]
WHEEL_JOINT_SIGNS = (1.0, 1.0, 1.0, 1.0)

# geometry (must match the URDF / robot_config.json)
WHEEL_RADIUS = 0.03028
"""Roller envelope radius [m] (CAD: 60.6 mm diameter)."""
WHEEL_BASE_HALF_LENGTH = 0.064
"""lx [m]."""
TRACK_HALF_WIDTH = 0.1526
"""ly [m]."""
WHEEL_Z = -0.0415
"""Wheel axle height w.r.t. the chassis center [m]."""
FOOTPRINT_HALF_EXTENTS = (0.133, 0.17)
"""Half length / width of the rectangle enclosing the robot incl. wheels [m] (assembly STL: 265.5 x 338.9 mm)."""

# motor: GUESS, a 12 V ~1:30 gear motor (JGB37-520 class)
MOTOR_NO_LOAD_SPEED = 35.0
"""[rad/s] (~1.06 m/s)."""
MOTOR_STALL_TORQUE = 1.5
"""[Nm]."""
WHEEL_EFFORT_LIMIT = 0.6
"""Continuous torque [Nm]; above the traction limit (~0.2 Nm per wheel at mu = 0.9, 3 kg), so wheels can slip."""
MAX_WHEEL_SPEED = 30.0
"""Maximum commanded wheel speed [rad/s] (~0.9 m/s)."""
WHEEL_DAMPING = 0.1
"""Velocity gain of the wheel speed controller [Nm*s/rad]; explicit-motor stability: d*dt/(I + armature) = 0.3."""
WHEEL_ARMATURE = 9.0e-4
"""Reflected rotor inertia [kg*m^2] (~1e-6 kg*m^2 rotor behind 1:30)."""
ROLLER_DAMPING = 1.0e-5
AXLE_JOINT_NAMES: list[str] = []
"""Rigid chassis: no pendulum axle."""

SPAWN_HEIGHT = WHEEL_RADIUS - WHEEL_Z + 0.005
"""Initial height of the base link [m] (5 mm above the ground contact)."""

# rubber-coated rollers: ~0.3 mm deflection under a quarter of the 3 kg weight (7.4 N)
ROLLER_CONTACT_STIFFNESS = 2.5e4
"""[N/m]; only effective on the ground material."""
ROLLER_CONTACT_DAMPING = 110.0
"""[N*s/m] (damping ratio ~0.4 with ~0.75 kg per wheel)."""
ROLLER_FRICTION = 0.9
"""Rubber on a hard floor (GUESS); the navigation task randomizes 0.5-1.1."""

ROBOT_MATERIAL = sim_utils.RigidBodyMaterialCfg(
    static_friction=ROLLER_FRICTION,
    dynamic_friction=ROLLER_FRICTION,
    friction_combine_mode="multiply",
    restitution_combine_mode="multiply",
    compliant_contact_stiffness=ROLLER_CONTACT_STIFFNESS,
    compliant_contact_damping=ROLLER_CONTACT_DAMPING,
)
"""Material of the robot colliders (set as the default material of the simulation, the URDF binds none)."""


def ground_material(friction: float = 1.0) -> sim_utils.RigidBodyMaterialCfg:
    """Ground material carrying the roller contact compliance (multiply-combined with the roller friction)."""
    return sim_utils.RigidBodyMaterialCfg(
        static_friction=friction,
        dynamic_friction=friction,
        friction_combine_mode="multiply",
        restitution_combine_mode="multiply",
        compliant_contact_stiffness=ROLLER_CONTACT_STIFFNESS,
        compliant_contact_damping=ROLLER_CONTACT_DAMPING,
    )


MECANUM_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        asset_path=str(URDF_PATH),
        fix_base=False,
        merge_fixed_joints=True,
        make_instanceable=True,
        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(
            target_type="velocity",
            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0.0, damping=0.0),
        ),
        activate_contact_sensors=False,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(disable_gravity=False, max_depenetration_velocity=1.0),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False, solver_position_iteration_count=8, solver_velocity_iteration_count=1
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(pos=(0.0, 0.0, SPAWN_HEIGHT), joint_pos={".*": 0.0}, joint_vel={".*": 0.0}),
    soft_joint_pos_limit_factor=1.0,
    actuators={
        "wheels": DCMotorCfg(
            joint_names_expr=WHEEL_JOINT_NAMES,
            stiffness=0.0,
            damping=WHEEL_DAMPING,
            saturation_effort=MOTOR_STALL_TORQUE,
            effort_limit=WHEEL_EFFORT_LIMIT,
            velocity_limit=MOTOR_NO_LOAD_SPEED,
            armature=WHEEL_ARMATURE,
        ),
        "rollers": ImplicitActuatorCfg(joint_names_expr=ROLLER_JOINT_NAMES, stiffness=0.0, damping=ROLLER_DAMPING),
    },
)
"""Our own mecanum robot, spawned from the generated URDF."""
